### ISSUE TITLE
Provide method to trigger a controller run

### ISSUE THREAD

**Issue by gregswift** [razee-io/razeedeploy-core#157]
**Is your feature request related to a problem? Please describe.**
Currently in razee with a 5 minute period on the controllers you can end up in a scenario where applying an update takes up to 15 minutes, depending on the order the controllers are running in and how far apart on their schedule.

In many traditional configuration management solutions there is a mechanism to trigger an ad-hoc run. The benefit of this is forcing a change to happen _right now_ rather than waiting for the timer to expire.

**Describe the solution you'd like**
The ability to call an API endpoint and trigger a run of a controller.

**Describe alternatives you've considered**
Just deleting the pods we want to re-run.  (does this have unforseen problems?)

**Comment by sdelmas** [comment]
Is this something that might happen any time soon, not demanding, I get the whole OSS thing. This is something that seems relevant for production systems, it certainly would help us.

**Comment by gregswift** [comment]
Another alternative that just got brought up was to add another label that causes razee, which is watching resources, to re-process that resource offcycle

**Comment by alewitt2** [comment]
you should be able to trigger mustacheTemplate to run by adding a label. When the fields defined [here](https://github.com/razee-io/razeedeploy-core/blob/41ec9dfa02425dc8513d59fa110a7c2b20bbef88/lib/BaseController.js#L237-L238) change, its supposed to allow the modified event to continue processing, instead of deeming it unimportant. For some reason, this seems to not be working on mustacheTemplate. Need to figure out why not.

**Comment by alewitt2** [comment]
i was unable to reproduce this bug while running locally. steps i ran through:
1. create mtp with a configmap as a template, and create an env configmap that the mtp uses to inject values into the new configmap template
2. verify the new configmap is created with the desired value
3. edit the env configmap with new value
4. update a label on the mtp to force it to run. ie. `kl label mtp rd-test razee/re-run="$(date +%s)" --overwrite`
5. verify the new configmap has the updated value

**Comment by gregswift** [comment]
This has worked ever since then.

thank ya!
