### ISSUE TITLE
Add user auth to RazeeDeploy components

### ISSUE THREAD

**Issue by alewitt2** [razee-io/razeedeploy-core#31]
Problem: there may be some cases where there is one kapitan that manages a cluster, but rbac that prevents some users from touching certain namespace. Currently a user could create a kapitan component in a ns they have access to, then have kapitan controller create resources in ns they dont have access to.

Possible solution: some kind of key dictionary the controller has access to that it will check against before creating a resource. ie. a user creates a managed set in default ns. the managed set is told to create a deployment in the kube-system ns. In order to do so, the managed set (or maybe the deployment) must have a key (as a label possibly) that gives it access to create in the other namespace

possible solution: check against rbac to see if the user(?) has access to create in the desired ns (not sure how to tie user to managedset to deployment yet).

**Comment by alewitt2** [comment]
possible solution: razee controller has a list of namespaces to accept input from, will ignore events from other namespaces

**Comment by mckaymic** [comment]
https://github.com/razee-io/Razee/issues/104

**Comment by carrolp** [comment]
Closing -- resolved by 104
