### ISSUE TITLE
Restrict Namespaces in which RazeeDeploy Resources will be processed

### ISSUE THREAD

**Issue by dgr237** [razee-io/razeedeploy-core#38]
We are looking to use Razee for the installation of a set of core services which are required. These core services are installed in some core namespaces which are protected (Developers who use the platform do not have access to these namespaces). 

As an alternative to creating complex RBAC rules we are proposing that the Razee components will only monitor certain restricted namespaces for MustacheTemplates, ManagedSets and the RemoteResources. 

This will therefore prevent users creating these resources which could potentially result in a privilege escalation.

**Comment by alewitt2** [comment]
common to #31. Will consider this as an option too.

**Comment by mckaymic** [comment]
https://github.com/razee-io/Razee/issues/104.
